### PR TITLE
Partially Migrate to Nextjs (App Routing)

### PR DESCRIPTION
**Pull request by yurakhomitsky**
- Partially migrated app to the Next js (App Routing)
- Application loads and displays movies with disabled Javascript
- Application allows us to select and see the selected movie with disabled Javascript

### CODE REVIEW

**Comment by igor-budzin** [comment]
There is an issue:
(JS is enabled, prod mode)

STR:
1) Click on any movie to open details
2) Reload page

Expected result 
After reload everything workd fine and movie details is open

Actual behaviour:
Page 404

**Comment by igor-budzin** [comment]
Another issue
(JS is enabled, prod mode)

STR:
1) Click on Add movie button

Actual behavior: 
Error

**Comment by igor-budzin** [comment]
Imposible editing movie, there is no menu anymore (JS is enabled, prod mode)

**Comment by igor-budzin** [comment]
Please fix issues so I can proceed with review

**Comment by yurakhomitsky** [comment]
> There is an issue: (JS is enabled, prod mode)
> 
> STR:
> 
> 1. Click on any movie to open details
> 2. Reload page
> 
> Expected result After reload everything workd fine and movie details is open
> 
> Actual behaviour: Page 404

I hope  I managed to fix this issue. Please rebase the branch

Regarding the Add and Edit movie this functionality is not going to be supported due to issues I have faced

**Review by igor-budzin — APPROVED** [review]

**Pull request merged**
